sudo: false

language: java
jdk: openjdk11

script:
  - if [ ! -z "$TRAVIS_PULL_REQUEST_BRANCH" ] then mvn package test; fi
  - if [ "$TRAVIS_BRANCH" = "develop" ] && if [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then mvn package test deploy; fi
  - if [ "$TRAVIS_BRANCH" = "master" ] && if [ -z "$TRAVIS_PULL_REQUEST_BRANCH" ]; then mvn package test -P release; fi
